### ISSUE TITLE
undefined reference to 'kversion'

### ISSUE THREAD

**Issue by Ruochen-Wang** [sklaw/enee447project7_hw_template_Shuangqi_sessions#1]
In trap_handler.c and kernel.c, kversion is called, but it's not defined, which causes a failure of makefile. Where and how should this 'kversion' be implemented?

**Comment by sklaw** [comment]
kversion is defined in a file called `kversion.c`, which is generated automatically through [this make command](https://github.com/sklaw/enee447project7_hw_template_Shuangqi_sessions/blob/master/Makefile#L32)

If you couldn't find `keversion.c` in your code directory, you could try to run `make kversion'.
